---
- name: Configure Cisco Router
  hosts: all
  gather_facts: false
  any_errors_fatal: true

  tasks:
  - name: load nat to web-server
    cisco.ios.ios_config:
      lines: ip nat inside source static tcp 10.0.0.5 80 interface g02 80
